apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: my-preview-apps
  namespace: argocd  
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - pullRequest:
      github:
        owner: codefresh-contrib
        repo: gitops-cert-level-3-examples
        labels:
          - preview
      requeueAfterSeconds: 180
  template:
    metadata:
      name: 'myapp-{{.branch}}'
    spec:
      source:
        repoURL: 'https://github.com/marcpires/gitops-cert-level-3-examples.git'
        targetRevision: HEAD
        path: preview-environments/kustomize-preview-app/ 
        kustomize:
          images:
            - 'docker.io/marcpires/my-preview-app:{{.branch_slug}}'
          # Mixes Argo and Kustomize manifests. NOT RECOMMENDED
          # Get a better way to do it
          patches:
            - target:
                kind: Deployment
                name: simple-deployment
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/0
                  value:
                    name: GIT_BRANCH
                    value: '{{.branch_slug}}'
                - op: replace
                  path: /spec/template/spec/containers/0/env/1
                  value:
                    name: GIT_HASH
                    value: '{{.head_short_sha_7}}'
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: 'preview-{{.branch_slug}}'
      syncPolicy:
        automated:
          prune: true  
        syncOptions:
        - CreateNamespace=true 
